
export interface questionResponse_M_DataInterface {
  QUESTION_SUB_HEADER: {
    QUESTION_DETAIL_ID_315: string;
    QUESTION_DETAIL_ID_331: string;
    QUESTION_DETAIL_ID_332: string;
    QUESTION_DETAIL_ID_311: string;
    QUESTION_DETAIL_ID_333: string;
    QUESTION_DETAIL_ID_312: string;
    QUESTION_DETAIL_ID_334: string;
    QUESTION_DETAIL_ID_313: string;
    QUESTION_DETAIL_ID_335: string;
    QUESTION_DETAIL_ID_314: string;
    QUESTION_DETAIL_ID_2: string;
    QUESTION_DETAIL_ID_6: string;
    QUESTION_DETAIL_ID_14: string;
    QUESTION_DETAIL_ID_15: string;
    QUESTION_DETAIL_ID_4: string;
    QUESTION_DETAIL_ID_12: string;
    QUESTION_DETAIL_ID_13: string;
    QUESTION_DETAIL_ID_9: string;
    QUESTION_DETAIL_ID_8: string;
    QUESTION_DETAIL_ID_7: string;
    QUESTION_DETAIL_ID_326: string;
    QUESTION_DETAIL_ID_10: string;
    QUESTION_DETAIL_ID_11: string;
    QUESTION_DETAIL_ID_441: string;
    QUESTION_DETAIL_ID_321: string;
    QUESTION_DETAIL_ID_442: string;
    QUESTION_DETAIL_ID_322: string;
    QUESTION_DETAIL_ID_443: string;
    QUESTION_DETAIL_ID_323: string;
    QUESTION_DETAIL_ID_444: string;
    QUESTION_DETAIL_ID_324: string;
    QUESTION_DETAIL_ID_445: string;
    QUESTION_DETAIL_ID_325: string;
  },
  CHOICES_OF_QUESTION: {
    CHOICES_OF_QUESTION_ID_10_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_10_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_14_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_14_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_14_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_335_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_14_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_335_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_14_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_335_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_335_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_335_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_444_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_444_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_10_VALUE_1_1: string;
    CHOICES_OF_QUESTION_ID_444_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_10_VALUE_1_2: string;
    CHOICES_OF_QUESTION_ID_444_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_444_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_226_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_332_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_332_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_332_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_332_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_332_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_6_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_6_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_226_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_226_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_226_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_226_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_114_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_114_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_114_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_114_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_114_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_222_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_222_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_222_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_222_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_2_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_222_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_2_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_2_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_445_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_111_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_445_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_111_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_445_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_111_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_445_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_111_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_445_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_441_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_441_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_7_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_441_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_7_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_441_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_441_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_13_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_13_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_13_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_111_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_225_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_331_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_225_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_331_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_225_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_331_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_225_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_331_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_225_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_221_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_115_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_115_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_115_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_115_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_115_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_221_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_221_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_221_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_221_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_331_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_112_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_112_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_112_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_112_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_112_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_8_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_442_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_442_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_442_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_442_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_442_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_8_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_8_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_224_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_224_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_4_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_224_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_4_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_224_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_224_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_334_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_334_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_334_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_15_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_334_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_15_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_334_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_113_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_113_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_113_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_113_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_113_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_9_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_11_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_443_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_11_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_9_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_443_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_443_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_11_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_443_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_443_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_11_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_11_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_333_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_333_VALUE_2: string;
    CHOICES_OF_QUESTION_ID_333_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_333_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_333_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_223_VALUE_5: string;
    CHOICES_OF_QUESTION_ID_223_VALUE_4: string;
    CHOICES_OF_QUESTION_ID_223_VALUE_1: string;
    CHOICES_OF_QUESTION_ID_223_VALUE_3: string;
    CHOICES_OF_QUESTION_ID_223_VALUE_2: string;
  },
  CHOICES_OF_REGIONAL_CENTER: {
    REGIONAL_NO: string;
    REGIONAL_NAME: string;
  },
  SECTION_MAIN_HEADER: {
    SECTION_NAME_ID_1: string;
    SECTION_NAME_ID_2: string;
    SECTION_NAME_ID_3: string;
  },
  CHOICES_OF_ALL_DISTRICT: {
    DISTRICT_NAME: string;
    AMPHUR_NAME: string;
    POSTCODE: string;
    DISTRICT_ID: string;
    AMPHUR_ID: string;
    PROVINCE_ID: string;
    COUNTRY_NAME_ENG: string;
    PROVINCE_NAME: string;
    COUNTRY_NO: string;
  },
  CHOICES_OF_DISTRICT: {
    DISTRICT_NAME: string;
  },
  CHOICES_OF_AMPHUR: {
    AMPHUR_NAME: string;
  },
  CHOICES_OF_PROVINCE: {
    PROVINCE_ID: string;
    PROVINCE_NAME: string;
  },
  CHOICES_OF_POSTCODE: {
    POSTCODE: string;
  },
  QUIZ_HEADER: string;
  question_error_message_status: number;
  LEV_ID: string;
  question_error_message: string;
}



export interface regional_M_Interface {
  REGIONAL_NO: string;
  REGIONAL_NAME: string;
}


export interface district_M_Interface {
  DISTRICT_NAME: string;
}

export interface amphur_M_Interface {
  AMPHUR_NAME: string;
}

export interface province_M_Interface {
  PROVINCE_ID: string;
  PROVINCE_NAME: string;
}

export interface postcode_M_Interface {
  POSTCODE: string;
}

export interface districtAll_M_Interface {
  DISTRICT_NAME: string;
  AMPHUR_NAME: string;
  POSTCODE: string;
  DISTRICT_ID: string;
  AMPHUR_ID: string;
  PROVINCE_ID: string;
  COUNTRY_NAME_ENG: string;
  PROVINCE_NAME: string;
  COUNTRY_NO: string;
}

export interface regional_M_Interface {
  REGIONAL_NO: string;
  REGIONAL_NAME: string;
}
